### ISSUE TITLE
A question about the paper 3D Deep Neural Network Segmentation of Intracerebral Hemorrhage: Development and Validation for Clinical Trials

### ISSUE THREAD

**Issue by Bigsealion** [msharrock/deepbleed#11]
In section `Pipeline Components`, I set you training the 128 network without Template Registration.

However, if you do not apply registration to the raw image, the shape of the input image can vary greatly (not 128*128*128) and is anisotropic, how to train 3d Vnet in this condition?

Thanks!

**Comment by muschellij2** [comment]
You need to resample the image still to 128^3 I believe.  Also, that may have been for the 2D net, but I have to check the paper.

**Comment by Bigsealion** [comment]
Thanks for your answer!
